apiVersion: v1
kind: Service
metadata:
  name: myportfolio
  labels:
    app: myportfolio
spec:
  type: LoadBalancer
  loadBalancerIP: 34.180.9.45
  selector:
    app: myportfolio
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
    - protocol: TCP
      port: 443
      targetPort: 443
      name: https
